spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mylibrary?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081


custom_property:
  secret_key: 1gf24r3hbhg6